// <auto-generated />
using System;
using HumioAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HumioAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260220112927_ProductSetManyToManyModules")]
    partial class ProductSetManyToManyModules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HumioAPI.Entities.AdminAccessHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("admin_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<long>("TargetUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_user_id");

                    b.HasKey("Id")
                        .HasName("pk_admin_access_history");

                    b.HasIndex("AdminId")
                        .HasDatabaseName("ix_admin_access_history_admin_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_admin_access_history_product_id");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("ix_admin_access_history_target_user_id");

                    b.ToTable("admin_access_history", null, t =>
                        {
                            t.HasCheckConstraint("ck_admin_access_history_days_positive", "days > 0");
                        });
                });

            modelBuilder.Entity("HumioAPI.Entities.Answer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_answers_question_id");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.AnswerLocalization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AnswerId")
                        .HasColumnType("bigint")
                        .HasColumnName("answer_id");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_text");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.HasKey("Id")
                        .HasName("pk_answer_localizations");

                    b.HasIndex("AnswerId")
                        .HasDatabaseName("ix_answer_localizations_answer_id");

                    b.HasIndex("AnswerId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_answer_localizations_answer_id_language_code");

                    b.ToTable("answer_localizations", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.ApplicationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<DateTimeOffset?>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_key");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("DeviceKey")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_device_key");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.Lesson", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsFree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_free");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_lessons_module_id");

                    b.HasIndex("ModuleId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_lessons_module_id_order_index");

                    b.ToTable("lessons", null, t =>
                        {
                            t.HasCheckConstraint("ck_lessons_duration_seconds_positive", "duration_seconds > 0");

                            t.HasCheckConstraint("ck_lessons_order_index_non_negative", "order_index >= 0");
                        });
                });

            modelBuilder.Entity("HumioAPI.Entities.LessonLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("LocalizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("localization_id");

                    b.Property<int>("Pos")
                        .HasColumnType("integer")
                        .HasColumnName("pos");

                    b.HasKey("Id")
                        .HasName("pk_lessons_links");

                    b.HasIndex("LocalizationId")
                        .HasDatabaseName("ix_lessons_links_localization_id");

                    b.HasIndex("LocalizationId", "Pos")
                        .IsUnique()
                        .HasDatabaseName("ix_lessons_links_localization_id_pos");

                    b.ToTable("lessons_links", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.LessonLocalization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AudioLink")
                        .HasColumnType("text")
                        .HasColumnName("audio_link");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<string>("TextContent")
                        .HasColumnType("text")
                        .HasColumnName("text_content");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_lessons_localizations");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_lessons_localizations_lesson_id");

                    b.HasIndex("LessonId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_lessons_localizations_lesson_id_language_code");

                    b.ToTable("lessons_localizations", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.Module", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_modules");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.ModuleLocalization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_module_localizations");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_module_localizations_module_id");

                    b.HasIndex("ModuleId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_module_localizations_module_id_language_code");

                    b.ToTable("module_localizations", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_product_set");

                    b.ToTable("product_set", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.ProductSetLocalization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("ProductSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_set_id");

                    b.HasKey("Id")
                        .HasName("pk_product_set_localizations");

                    b.HasIndex("ProductSetId")
                        .HasDatabaseName("ix_product_set_localizations_product_set_id");

                    b.HasIndex("ProductSetId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_product_set_localizations_product_set_id_language_code");

                    b.ToTable("product_set_localizations", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.Promocode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<int>("MaxUsageCount")
                        .HasColumnType("integer")
                        .HasColumnName("max_usage_count");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_promocodes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_promocodes_code");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_promocodes_product_id");

                    b.ToTable("promocodes", null, t =>
                        {
                            t.HasCheckConstraint("ck_promocodes_days_positive", "days > 0");

                            t.HasCheckConstraint("ck_promocodes_max_usage_count_positive", "max_usage_count > 0");
                        });
                });

            modelBuilder.Entity("HumioAPI.Entities.PromocodeUsage", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("PromocodeId")
                        .HasColumnType("bigint")
                        .HasColumnName("promocode_id");

                    b.Property<DateTimeOffset>("UsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "PromocodeId")
                        .HasName("pk_promocode_usages");

                    b.HasIndex("PromocodeId")
                        .HasDatabaseName("ix_promocode_usages_promocode_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_promocode_usages_user_id");

                    b.ToTable("promocode_usages", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.Purchase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_payment_id");

                    b.Property<DateTimeOffset?>("PurchasedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at");

                    b.Property<string>("Receipt")
                        .HasColumnType("text")
                        .HasColumnName("receipt");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_purchases");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_purchases_product_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_purchases_user_id");

                    b.HasIndex("Provider", "ProviderPaymentId")
                        .IsUnique()
                        .HasDatabaseName("ix_purchases_provider_provider_payment_id");

                    b.ToTable("purchases", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchases_amount_cents_non_negative", "amount_cents >= 0");

                            t.HasCheckConstraint("ck_purchases_currency_iso", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_purchases_days_positive", "days > 0");

                            t.HasCheckConstraint("ck_purchases_status", "status IN ('pending','paid','failed','refunded')");
                        });
                });

            modelBuilder.Entity("HumioAPI.Entities.Question", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<long>("LessonId")
                        .HasColumnType("bigint")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_questions_lesson_id");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.QuestionLocalization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language_code");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.HasKey("Id")
                        .HasName("pk_question_localizations");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_localizations_question_id");

                    b.HasIndex("QuestionId", "LanguageCode")
                        .IsUnique()
                        .HasDatabaseName("ix_question_localizations_question_id_language_code");

                    b.ToTable("question_localizations", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<long?>("ReplacedByTokenId")
                        .HasColumnType("bigint")
                        .HasColumnName("replaced_by_token_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_refresh_tokens_device_id");

                    b.HasIndex("ReplacedByTokenId")
                        .HasDatabaseName("ix_refresh_tokens_replaced_by_token_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.UserDevice", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("DeviceId")
                        .HasColumnType("bigint")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "DeviceId")
                        .HasName("pk_users_devices");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_users_devices_device_id");

                    b.ToTable("users_devices", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.UserModuleAccess", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("module_id");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.HasKey("UserId", "ModuleId")
                        .HasName("pk_user_module_access");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_user_module_access_module_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_module_access_user_id");

                    b.ToTable("user_module_access", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.UserProfile", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("text")
                        .HasColumnName("middle_name");

                    b.HasKey("UserId")
                        .HasName("pk_user_profiles");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("ProductSetModule", b =>
                {
                    b.Property<long>("ProductSetId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_set_id");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint")
                        .HasColumnName("module_id");

                    b.HasKey("ProductSetId", "ModuleId")
                        .HasName("pk_product_set_modules");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_product_set_modules_module_id");

                    b.ToTable("product_set_modules", (string)null);
                });

            modelBuilder.Entity("HumioAPI.Entities.AdminAccessHistory", b =>
                {
                    b.HasOne("HumioAPI.Entities.ApplicationUser", "Admin")
                        .WithMany("AdminAccessEntries")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_access_history_users_admin_id");

                    b.HasOne("HumioAPI.Entities.Product", "Product")
                        .WithMany("AdminAccessHistory")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_admin_access_history_products_product_id");

                    b.HasOne("HumioAPI.Entities.ApplicationUser", "TargetUser")
                        .WithMany("TargetAccessEntries")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_admin_access_history_users_target_user_id");

                    b.Navigation("Admin");

                    b.Navigation("Product");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("HumioAPI.Entities.Answer", b =>
                {
                    b.HasOne("HumioAPI.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answers_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HumioAPI.Entities.AnswerLocalization", b =>
                {
                    b.HasOne("HumioAPI.Entities.Answer", "Answer")
                        .WithMany("Localizations")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answer_localizations_answers_answer_id");

                    b.Navigation("Answer");
                });

            modelBuilder.Entity("HumioAPI.Entities.Lesson", b =>
                {
                    b.HasOne("HumioAPI.Entities.Module", "Module")
                        .WithMany("Lessons")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("HumioAPI.Entities.LessonLink", b =>
                {
                    b.HasOne("HumioAPI.Entities.LessonLocalization", "Localization")
                        .WithMany("Links")
                        .HasForeignKey("LocalizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_links_lessons_localizations_localization_id");

                    b.Navigation("Localization");
                });

            modelBuilder.Entity("HumioAPI.Entities.LessonLocalization", b =>
                {
                    b.HasOne("HumioAPI.Entities.Lesson", "Lesson")
                        .WithMany("Localizations")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lessons_localizations_lessons_lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("HumioAPI.Entities.ModuleLocalization", b =>
                {
                    b.HasOne("HumioAPI.Entities.Module", "Module")
                        .WithMany("Localizations")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_module_localizations_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("HumioAPI.Entities.ProductSetLocalization", b =>
                {
                    b.HasOne("HumioAPI.Entities.Product", "ProductSet")
                        .WithMany("Localizations")
                        .HasForeignKey("ProductSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_set_localizations_products_product_set_id");

                    b.Navigation("ProductSet");
                });

            modelBuilder.Entity("HumioAPI.Entities.Promocode", b =>
                {
                    b.HasOne("HumioAPI.Entities.Product", "Product")
                        .WithMany("Promocodes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promocodes_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HumioAPI.Entities.PromocodeUsage", b =>
                {
                    b.HasOne("HumioAPI.Entities.Promocode", "Promocode")
                        .WithMany("Usages")
                        .HasForeignKey("PromocodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promocode_usages_promocodes_promocode_id");

                    b.HasOne("HumioAPI.Entities.ApplicationUser", "User")
                        .WithMany("PromocodeUsages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promocode_usages_users_user_id");

                    b.Navigation("Promocode");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumioAPI.Entities.Purchase", b =>
                {
                    b.HasOne("HumioAPI.Entities.Product", "Product")
                        .WithMany("Purchases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchases_products_product_id");

                    b.HasOne("HumioAPI.Entities.ApplicationUser", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchases_users_user_id");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumioAPI.Entities.Question", b =>
                {
                    b.HasOne("HumioAPI.Entities.Lesson", "Lesson")
                        .WithMany("Questions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_lessons_lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("HumioAPI.Entities.QuestionLocalization", b =>
                {
                    b.HasOne("HumioAPI.Entities.Question", "Question")
                        .WithMany("Localizations")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_localizations_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HumioAPI.Entities.RefreshToken", b =>
                {
                    b.HasOne("HumioAPI.Entities.Device", "Device")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_refresh_tokens_devices_device_id");

                    b.HasOne("HumioAPI.Entities.RefreshToken", "ReplacedByToken")
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_refresh_tokens_refresh_tokens_replaced_by_token_id");

                    b.HasOne("HumioAPI.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("Device");

                    b.Navigation("ReplacedByToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumioAPI.Entities.UserDevice", b =>
                {
                    b.HasOne("HumioAPI.Entities.Device", "Device")
                        .WithMany("UserDevices")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_devices_devices_device_id");

                    b.HasOne("HumioAPI.Entities.ApplicationUser", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_devices_users_user_id");

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumioAPI.Entities.UserModuleAccess", b =>
                {
                    b.HasOne("HumioAPI.Entities.Module", "Module")
                        .WithMany("UserModuleAccesses")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_module_access_modules_module_id");

                    b.HasOne("HumioAPI.Entities.ApplicationUser", "User")
                        .WithMany("ModuleAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_module_access_users_user_id");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HumioAPI.Entities.UserProfile", b =>
                {
                    b.HasOne("HumioAPI.Entities.ApplicationUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("HumioAPI.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("HumioAPI.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("HumioAPI.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("HumioAPI.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("HumioAPI.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("HumioAPI.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("HumioAPI.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("ProductSetModule", b =>
                {
                    b.HasOne("HumioAPI.Entities.Module", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_set_modules_modules_module_id");

                    b.HasOne("HumioAPI.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_set_modules_product_set_product_set_id");
                });

            modelBuilder.Entity("HumioAPI.Entities.Answer", b =>
                {
                    b.Navigation("Localizations");
                });

            modelBuilder.Entity("HumioAPI.Entities.ApplicationUser", b =>
                {
                    b.Navigation("AdminAccessEntries");

                    b.Navigation("ModuleAccesses");

                    b.Navigation("Profile");

                    b.Navigation("PromocodeUsages");

                    b.Navigation("Purchases");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TargetAccessEntries");

                    b.Navigation("UserDevices");
                });

            modelBuilder.Entity("HumioAPI.Entities.Device", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserDevices");
                });

            modelBuilder.Entity("HumioAPI.Entities.Lesson", b =>
                {
                    b.Navigation("Localizations");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("HumioAPI.Entities.LessonLocalization", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("HumioAPI.Entities.Module", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Localizations");

                    b.Navigation("UserModuleAccesses");
                });

            modelBuilder.Entity("HumioAPI.Entities.Product", b =>
                {
                    b.Navigation("AdminAccessHistory");

                    b.Navigation("Localizations");

                    b.Navigation("Promocodes");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("HumioAPI.Entities.Promocode", b =>
                {
                    b.Navigation("Usages");
                });

            modelBuilder.Entity("HumioAPI.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Localizations");
                });
#pragma warning restore 612, 618
        }
    }
}
